services:
  - type: web
    name: client
    env: static
    staticPublishPath: packages/client/build
    buildCommand: npm run build --prefix packages/client
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: api-svc
    env: node
    buildCommand: npm install --prefix packages/svc-api && npm run build --prefix packages/svc-api
    start: npm start --prefix packages/svc-api
    routes:
      - type: rewrite
        source: /api/*
        destination: /