// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Piece, PieceData } from "./tables/Piece.sol";
import { PlayerPiece } from "./tables/PlayerPiece.sol";
