// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PieceTypes } from "../../libraries/PieceTypes.sol";

/**
 * @title IPieceSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPieceSystem {
  function app__createPiece(
    string memory name,
    string memory image,
    string memory movementAbility,
    string memory captureAbility,
    PieceTypes.ComponentData[] memory components
  ) external;

  function app__givePieceToPlayer(address ownerAddress, bytes32 pieceId, uint256 quantity) external;
}
