// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IPieceSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPieceSystem {
  function app__createPiece(
    address owner,
    string memory name,
    string memory movementAbility,
    string memory captureAbility
  ) external;
}
