// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PieceTypes } from "../../libraries/PieceTypes.sol";

/**
 * @title ISquadSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISquadSystem {
  function app__createSquad(string memory name, PieceTypes.SquadPieceData[] memory pieces) external returns (bytes32);
}
